export const GET_CLASSES = 'GET_CLASSES';
export const GET_CLASSES_COMPLETE = 'GET_CLASSES_COMPLETE';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';
export const SUBSCRIBE_TO_CLASS = 'SUBSCRIBE_TO_CLASS';